apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe645-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swe645-app
  template:
    metadata:
      labels:
        app: swe645-app
    spec:
      containers:
      - name: swe645-container
        image: rajaditya079/swe645-webapp:v1
        ports:
        - containerPort: 80
